[workspace]
members = [
  "rust",
]
resolver = "2"

[workspace.package]
authors = ["ONEKEY <support@onekey.com>"]
edition = "2021"
license = "MIT"
publish = false
rust-version = "1.82.0"
version = "0.0.0"
